const minion_slots = {
  0: 5,
  5: 6,
  15: 7,
  30: 8,
  50: 9,
  75: 10,
  100: 11,
  125: 12,
  150: 13,
  175: 14,
  200: 15,
  225: 16,
  250: 17,
  275: 18,
  300: 19,
  350: 20,
  400: 21,
  450: 22,
  500: 23,
  550: 24,
  600: 25,
  650: 26,
  700: 27,
  750: 28,
  800: 29,
  850: 30,
};

const minions = {
  FLOWER: {
    id: "FLOWER",
    name: "Flower",
    category: "foraging",
    maxLevel: 12,
    emoji: "YELLOW_FLOWER",
  },
  TARANTULA: {
    id: "TARANTULA",
    name: "Tarantula",
    category: "combat",
    maxLevel: 11,
    emoji: "ENCHANTED_STRING",
  },
  GRAVEL: {
    id: "GRAVEL",
    name: "Gravel",
    category: "mining",
    maxLevel: 11,
  },
  COCOA: {
    id: "COCOA",
    name: "Cocoa Beans",
    category: "farming",
    maxLevel: 12,
    emoji: "INK_SACK:3",
  },
  FISHING: {
    id: "FISHING",
    name: "Raw Fish",
    category: "fishing",
    maxLevel: 11,
    emoji: "RAW_FISH",
  },
  ICE: {
    id: "ICE",
    name: "Ice",
    category: "mining",
    maxLevel: 11,
  },
  SLIME: {
    id: "SLIME",
    name: "Slime",
    category: "combat",
    maxLevel: 11,
    emoji: "SLIME_BALL",
  },
  PUMPKIN: {
    id: "PUMPKIN",
    name: "Pumpkin",
    category: "farming",
    maxLevel: 12,
  },
  COBBLESTONE: {
    id: "COBBLESTONE",
    name: "Cobblestone",
    category: "mining",
    maxLevel: 12,
  },
  GLOWSTONE: {
    id: "GLOWSTONE",
    name: "Glowstone",
    category: "mining",
    maxLevel: 12,
  },
  DIAMOND: {
    id: "DIAMOND",
    name: "Diamond",
    category: "mining",
    maxLevel: 12,
  },
  DARK_OAK: {
    id: "DARK_OAK",
    name: "Dark Oak",
    category: "foraging",
    maxLevel: 11,
    emoji: "LOG_2:1",
  },
  GOLD: {
    id: "GOLD",
    name: "Gold Ingot",
    category: "mining",
    maxLevel: 12,
    emoji: "GOLD_INGOT",
  },
  REVENANT: {
    id: "REVENANT",
    name: "Revenant",
    category: "combat",
    maxLevel: 12,
    emoji: "REVENANT_FLESH",
  },
  CHICKEN: {
    id: "CHICKEN",
    name: "Chicken",
    category: "farming",
    maxLevel: 12,
    emoji: "RAW_CHICKEN",
  },
  CAVESPIDER: {
    id: "CAVESPIDER",
    name: "Cave Spider",
    category: "combat",
    maxLevel: 11,
    emoji: "SPIDER_EYE",
  },
  BLAZE: {
    id: "BLAZE",
    name: "Blaze",
    category: "combat",
    maxLevel: 12,
    emoji: "BLAZE_ROD",
  },
  CLAY: {
    id: "CLAY",
    name: "Clay",
    category: "fishing",
    maxLevel: 11,
    emoji: "CLAY_BALL",
  },
  CACTUS: {
    id: "CACTUS",
    name: "Cactus",
    category: "farming",
    maxLevel: 12,
  },
  PIG: {
    id: "PIG",
    name: "Porkchop",
    category: "farming",
    maxLevel: 12,
    emoji: "PORK",
  },
  ENDERMAN: {
    id: "ENDERMAN",
    name: "Enderman",
    category: "combat",
    maxLevel: 11,
    emoji: "ENDER_PEARL",
  },
  COAL: {
    id: "COAL",
    name: "Coal",
    category: "mining",
    maxLevel: 12,
  },
  WHEAT: {
    id: "WHEAT",
    name: "Wheat",
    category: "farming",
    maxLevel: 12,
  },
  REDSTONE: {
    id: "REDSTONE",
    name: "Redstone",
    category: "mining",
    maxLevel: 12,
  },
  JUNGLE: {
    id: "JUNGLE",
    name: "Jungle Wood",
    category: "foraging",
    maxLevel: 11,
    emoji: "LOG:3",
  },
  SKELETON: {
    id: "SKELETON",
    name: "Skeleton",
    category: "combat",
    maxLevel: 11,
    emoji: "BONE",
  },
  LAPIS: {
    id: "LAPIS",
    name: "Lapis Lazuli",
    category: "mining",
    maxLevel: 12,
    emoji: "INK_SACK:4",
  },
  RABBIT: {
    id: "RABBIT",
    name: "Rabbit",
    category: "farming",
    maxLevel: 12,
  },
  SUGAR_CANE: {
    id: "SUGAR_CANE",
    name: "Sugar Cane",
    category: "farming",
    maxLevel: 12,
  },
  MELON: {
    id: "MELON",
    name: "Melon",
    category: "farming",
    maxLevel: 12,
  },
  NETHER_WARTS: {
    id: "NETHER_WARTS",
    name: "Nether Wart",
    category: "farming",
    maxLevel: 12,
    emoji: "NETHER_STALK",
  },
  QUARTZ: {
    id: "QUARTZ",
    name: "Quartz",
    category: "mining",
    maxLevel: 12,
  },
  CREEPER: {
    id: "CREEPER",
    name: "Creeper",
    category: "combat",
    maxLevel: 11,
    emoji: "SULPHUR",
  },
  OAK: {
    id: "OAK",
    name: "Oak Wood",
    category: "foraging",
    maxLevel: 11,
    emoji: "LOG",
  },
  MUSHROOM: {
    id: "MUSHROOM",
    name: "Mushroom",
    category: "farming",
    maxLevel: 12,
    emoji: "RED_MUSHROOM",
  },
  SNOW: {
    id: "SNOW",
    name: "Snow",
    category: "mining",
    maxLevel: 11,
    emoji: "SNOW_BALL",
  },
  POTATO: {
    id: "POTATO",
    name: "Potato",
    category: "farming",
    maxLevel: 12,
    emoji: "POTATO_ITEM",
  },
  MAGMA_CUBE: {
    id: "MAGMA_CUBE",
    name: "Magma Cube",
    category: "combat",
    maxLevel: 12,
    emoji: "MAGMA_CREAM",
  },
  ZOMBIE: {
    id: "ZOMBIE",
    name: "Zombie",
    category: "combat",
    maxLevel: 11,
    emoji: "ROTTEN_FLESH",
  },
  SPRUCE: {
    id: "SPRUCE",
    name: "Spruce Wood",
    category: "foraging",
    maxLevel: 11,
    emoji: "LOG:1",
  },
  SAND: {
    id: "SAND",
    name: "Sand",
    category: "mining",
    maxLevel: 11,
  },
  EMERALD: {
    id: "EMERALD",
    name: "Emerald",
    category: "mining",
    maxLevel: 12,
  },
  CARROT: {
    id: "CARROT",
    name: "Carrot",
    category: "farming",
    maxLevel: 12,
    emoji: "CARROT_ITEM",
  },
  ENDER_STONE: {
    id: "ENDER_STONE",
    name: "Endstone",
    category: "mining",
    maxLevel: 11,
  },
  BIRCH: {
    id: "BIRCH",
    name: "Birch Wood",
    category: "foraging",
    emoji: "LOG:2",
  },
  GHAST: {
    id: "GHAST",
    name: "Ghast",
    category: "combat",
    maxLevel: 12,
    emoji: "GHAST_TEAR",
  },
  SPIDER: {
    id: "SPIDER",
    name: "Spider",
    category: "combat",
    maxLevel: 11,
    emoji: "STRING",
  },
  IRON: {
    id: "IRON",
    name: "Iron Ingot",
    category: "mining",
    maxLevel: 12,
    emoji: "IRON_INGOT",
  },
  SHEEP: {
    id: "SHEEP",
    name: "Mutton",
    category: "farming",
    maxLevel: 12,
    emoji: "MUTTON",
  },
  ACACIA: {
    id: "ACACIA",
    name: "Acacia Wood",
    category: "foraging",
    maxLevel: 11,
    emoji: "LOG_2",
  },
  OBSIDIAN: {
    id: "OBSIDIAN",
    name: "Obsidian",
    category: "mining",
    maxLevel: 12,
  },
  COW: {
    id: "COW",
    name: "Cow",
    category: "farming",
    maxLevel: 12,
    emoji: "RAW_BEEF",
  },
  MITHRIL: {
    id: "MITHRIL",
    name: "Mithril",
    category: "mining",
    maxLevel: 12,
    emoji: "MITHRIL_ORE",
  },
  HARD_STONE: {
    id: "HARD_STONE",
    name: "Hard Stone",
    category: "mining",
    maxLevel: 12,
  },
  INFERNO: {
    id: "INFERNO",
    name: "Inferno",
    category: "combat",
    maxLevel: 11,
    emoji: "CRUDE_GABAGOOL",
  },
  RED_SAND: {
    id: "RED_SAND",
    name: "Red Sand",
    category: "mining",
    maxLevel: 12,
    emoji: "SAND:1",
  },
  MYCELIUM: {
    id: "MYCELIUM",
    name: "Mycelium",
    category: "mining",
    maxLevel: 12,
    emoji: "MYCEL",
  },
  VOIDLING: {
    id: "VOIDLING",
    name: "Voidling",
    category: "combat",
    maxLevel: 11,
    emoji: "NULL_SPHERE"
  }
};

module.exports = { minions, minion_slots }