module.exports = {
  trophy_fish: {
    BLOBFISH: {
      name: "Blobfish",
      id: "BLOBFISH",
      description: "Chances: **15%**\nCaught everywhere.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    FLYFISH: {
      name: "Flyfish",
      id: "FLYFISH",
      description: "Chances: **8%**\nCaught from \`8\` blocks or higher above lava in the Blazing Volcano.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    GOLDEN_FISH: {
      name: "Golden Fish",
      id: "GOLDEN_FISH",
      description: "Chances: **None**\nHas a chance to spawn after \`15\` minutes of fishing, increasing linearly until reaching 100% at 20 minutes.\nThe Golden Fish is rolled when your fishing hook is thrown out, regardless of if you catch a fish or not. You are not required to Trophy Fish to catch this one",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    GUSHER: {
      name: "Gusher",
      id: "GUSHER",
      description: "Chances: **20%**\nCaught within \`7-16\` minutes after a Blazing Volcano eruption.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    KARATE_FISH: {
      name: "Karate Fish",
      id: "KARATE_FISH",
      description: "Chances: **1%**\nCaught in the lava pools near the Dojo.\nNote - Half of the lava pools do not actually count as being in the Dojo area. If you stand in the same place as your bobber and do not see 'Dojo' in the sidebar, you cannot catch the Karate Fish there.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    LAVA_HORSE: {
      name: "Lavahorse",
      id: "LAVA_HORSE",
      description: "Chances: **4%**\nCaught everywhere.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    MANA_RAY: {
      name: "Mana Ray",
      id: "MANA_RAY",
      description: "Chances: **4%**\nCaught when you have at least \`1,200\` Mana.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    MOLDFIN: {
      name: "Moldfin",
      id: "MOLDFIN",
      description: "Chances: **2%**\nCaught in the Mystic Marsh.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    OBFUSCATED_FISH_1: {
      name: "Obfuscated Fish 1",
      id: "OBFUSCATED_FISH_1",
      description: "Chances: **25%**\nCaught with Corrupted Bait.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    OBFUSCATED_FISH_2: {
      name: "Obfuscated Fish 2",
      id: "OBFUSCATED_FISH_2",
      description: "Chances: **20%**\nCaught whilst using Obfuscated 1 as bait.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    OBFUSCATED_FISH_3: {
      name: "Obfuscated Fish 3",
      id: "OBFUSCATED_FISH_3",
      description: "Chances: **10%**\nCaught whilst using Obfuscated \`2\` as bait.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    SKELETON_FISH: {
      name: "Skeleton Fish",
      id: "SKELETON_FISH",
      description: "Chances: **2%**\nCaught in the Burning Desert.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    SLUGFISH: {
      name: "Slugfish",
      id: "SLUGFISH",
      description: "Chances: **10%**\nCaught when the bobber has been active for at least \`30\` seconds.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    SOUL_FISH: {
      name: "Soul Fish",
      id: "SOUL_FISH",
      description: "Chances: **2%**\nCaught in the Stronghold.", 
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    STEAMING_HOT_FLOUNDER: {
      name: "Steaming Hot Flounder",
      id: "STEAMING_HOT_FLOUNDER",
      description: "Chances: **20%**\nCaught when the bobber is within \`2\` blocks of a Geyser in the Blazing Volcano.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    SULPHUR_SKITTER: {
      name: "Sulphur Skitter",
      id: "SULPHUR_SKITTER",
      description: "Chances: **30%**\nCaught when standing within \`8\` blocks of a Sulphur Ore.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    VANILLE: {
      name: "Vanille",
      id: "VANILLE",
      description: "Chances: **3%**\nCaught when using a Starter Lava Rod with no Enchantments.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
    VOLCANIC_STONEFISH: {
      name: "Volcanic Stonefish",
      id: "VOLCANIC_STONEFISH",
      description: "Chances: **3%**\nCaught in the Blazing Volcano.",
      total: 0,
      bronze: 0,
      silver: 0,
      gold: 0,
      diamond: 0,
    },
  },
};
